### ISSUE TITLE
Conflicting focus/outline styles on download buttons

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#286]
**Operating system, Browser, Browser Version:**
Windows 10, Chrome 88.0.4324.104

**Issue description:**
https://godotengine.org/download

Download Godot buttons seem to have conflicting styles giving some weird inset/outset effect to them. It looks like there is an offset to the anchor tag inside of the button which makes the background to shine through (the darker border on screenshots). When you grab the focus of the button an additional outline is applied with
```css
*:focus {
  /* More visible outline for better keyboard navigation. */
  outline: 0.125rem solid hsl(220, 100%, 62.5%);
  /* Make the outline always appear above other elements. */
  /* Otherwise, one of its sides can be hidden by tabs in the Download and More layouts. */
  position: relative;
}
```

With that additional outline another part of the offset becomes visible, where the underlying 2px wide outline shines through. Combined this creates an old-schoold outset affect a-la Win 95.

**Screenshots (greatly appreciated if it’s a style issue)**
![image](https://user-images.githubusercontent.com/11782833/107043700-6a5adf00-67d4-11eb-8f90-e6b0c22f567d.png)
![chrome_2021-02-05_16-51-48](https://user-images.githubusercontent.com/11782833/107044169-fe2cab00-67d4-11eb-9d3a-67ccc596c178.png)

A better visualization with some styles stripped:
![2021-02-05_17-00-37](https://user-images.githubusercontent.com/11782833/107043603-4dbea700-67d4-11eb-9fa4-c9ac79197644.gif)

Offset is also affected by relative position on the page and the size:
![2021-02-05_16-56-17](https://user-images.githubusercontent.com/11782833/107044285-21575a80-67d5-11eb-92a4-defc55253636.gif)
