### ISSUE TITLE
Navigation links scroll too far down the page

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-website#77]
**Operating system, Browser, Browser Version:** Firefox 65 from Ubuntu repos

**Issue description:** On an article such as [this one](https://godotengine.org/article/godot-3-1-released), clicking one of the navigation links scrolls too far down the page. The title of the section ends up beneath the navbar.

**Screenshots (greatly appreciated if it’s a style issue):** Clicking "OpenGL ES 2.0 renderer":
![1](https://user-images.githubusercontent.com/1646875/54468005-3c430080-475f-11e9-8340-32aeaaa54083.png)

**Comment by Calinou** [comment]
This could be fixed in two ways:

1. Add the following CSS snippet:

```css
/* Adjust anchor link location to not cover titles with header */
:target:before {
  content: "";
  display: block;
  height: 60px; 
  margin: -60px 0 0;
}
```

2. Make the navigation bar static (i.e. not fixed). This is probably a better choice in 2019 — a lot of websites are going back to static navigation bars these days, because vertical real estate is precious.
